language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install -r requirements_travis.txt
script:
  - py.test penkit --doctest-modules
  - python setup.py install
  - sed -n 's/    //p' README.rst | python
