language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install -r travis_requirements.txt
script:
  - py.test penkit --doctest-modules
  - python setup.py install
  - PYTHONPATH=. py.test --doctest-glob="*.rst"
