language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install -r requirements_travis.txt
script:
  - py.test penkit --doctest-modules
  - python setup.py install
  - sphinx-build -b doctest -C -Dmaster_doc=README -Dextensions=sphinx.ext.doctest ./ /tmp/ README.rst
